### PR TITLE
Updated S3 Credentials management

### PR DESCRIPTION
**Pull request by jcsekar**
Updated S3 Credentials management as it has been updated as given in quantumblacklabs/kedro#539

### CODE REVIEW

**Review by lorenabalan — APPROVED** [review]
Thank you!! ⭐

**Comment by jcsekar** [comment]
@lorenabalan Could you please merge this PR to master?

**Comment by jcsekar** [comment]
@lorenabalan ,
Could you please add hacktoberfest-accepted label to this PR if you wish to?

**Comment by lorenabalan** [comment]
Done! 😊

**Pull request merged**
